host: localhost
port: 4000  

name: Taylor Burgess
author: Taylor Burgess

permalink: pretty

highlighter: rouge

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: _assets/css/_sass
    style: compressed

gems:
  - jekyll-feed
