# Harmony Jekyll theme general configurations 

# Localhost 
host: localhost
port: 4000  

name: Taylor Burgess
author: Taylor Burgess

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Taylor Burgess

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

gems:
  - jekyll-feed
