host: localhost
port: 4000  

name: Taylor Burgess
author: Taylor Burgess

permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: assets/css/_sass
    style: :compressed

gems:
  - jekyll-feed
